import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import SigninPage from "./(auth)/signin/page";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose the weights you need
});

export const metadata = {
  title: "Caffeine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} min-h-screen md:pl-60 bg-[#F5F6F8] antialiased`}
        suppressHydrationWarning={true}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
